[general]
	#The CurseForge project ID for the ___modpack
	#Range: > 0
	modpackProjectID = 572984
	#The name of the ___modpack
	modpackName = "uBingo"
	#The version of the ___modpack
	modpackVersion = "v1.5.4"
	#Use the metadata.json to determine the ___modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = true
