branches;
  - label: features
    prefix: feature/
  - label: bugs
    prefix: fix/ 
  - label: question
    skip: true
branchName: 'issue/${issue.number}'
defaultBranch: 'dev'
mode: chatops
autoCloseIssue: true
openPR: true
copyIssueDescriptionToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true
