name = "uBingo"
author = "Jqshuv"
version = "2.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1eaf1200599e768ee10c4d84e3bf3cac044818c8a4501c10d681e26a4dd1a2f1"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
