name = "uBingo"
author = "Jqshuv"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "059af748b22fdc13cdbdad3e94562a9fad3e7b1d348613ca2bfb4dae2cc93c05"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
