name = "uBingo"
author = "Jqshuv"
version = "2.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "990b8e3f6b08f7fcb524634e018ec1ceb9a0238a14a67d3dbf0ccff9372af634"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
