name: Bug Report
description: Submit a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: So, what did exactly happend?      
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Modpack Version
      description: What version of uBingo are you running?
      options:
        - 1.3.x
        - 1.2.x
        - 1.1.x
        - 1.0.x
    validations:
      required: true
  - type: dropdown
    id: mc-version
    attributes:
      label: Minecraft Version
      description: In which Minecraft version did the bug happend?
      options:
        - 1.18.2
        - 1.18.1
        - 1.18
    validations:
      required: true
  - type: dropdown
    id: playmode
    attributes:
      label: Did it happend in multiplayer, singleplayer or in both?
      multiple: true
      options:
        - Multiplayer
        - Singleplayer
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please paste any relevant log output. This will be automatically formatted into code, so no need for backticks. (If it happend on Multiplayer and you have permissions you can also use **/mclogs**)
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Review
      description: By submitting this issue, you agree that you checked the following.
      options:
        - label: I agree to follow this project's (Code of Conduct)[https://www.contributor-covenant.org/]
          required: true
        - label: I've checked that this bug is not already submitted. ((Issues)[https://github.com/Unately/uBingo/issues])
          required: true
        - label: I believe this is a bug with the software or mods and not with my system.
          required: true