# Early loading screen configuration file
# reuse_early_window default: true
# enable_entrypoint_information default: true
# enable_mixin_pretransform default: false
# allow_early_window_close default: true
# window_creation_point available [default] options: postModLoading mixinEarly [mixinLoad] preLaunch mcEarly off
#
#Sun Feb 23 21:27:54 CET 2025
allow_early_window_close=default
enable_entrypoint_information=default
enable_mixin_pretransform=default
reuse_early_window=default
window_creation_point=default
