#Configuration file for VMP
#Wed Mar 05 16:47:25 CET 2025
optimized_entity_tracking_use_staging_area=true
show_async_loading_messages=false
show_chunk_tracking_messages=false
target_chunk_send_rate=-1
use_async_chunks_on_login=false
use_async_chunks_on_some_commands=false
use_async_logging=true
use_async_portals=true
use_multiple_netty_event_loops=false
use_optimized_entity_tracking=true
