#Server Country Flags properties file
#Mon Feb 24 16:27:35 CET 2025
borderColor=(65, 65, 65, 255)
displayCooldownFlag=true
displayUnknownFlag=true
flagBorder=true
flagPosition=behindName
forceEnglish=false
mapButton=false
mapButtonRight=true
reloadOnRefresh=false
resolveRedirects=true
serverBrowserIntegration=true
showDistance=false
showDistrict=false
showHomeOnMap=false
showISP=false
useKm=true
