name = "uBingo"
author = "Jqshuv"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22f178ca7d04db19fb38122bb5988aa57e7fbc2df0f199e4aaef1bfe4b451423"

[versions]
forge = "40.0.54"
minecraft = "1.18.2"
