
#Gamerules that are set when a world is loaded
[gamerules]
	announce_advancements = false
	command_block_output = false
	disable_elytra_movement_check = true
	log_admin_commands = true
#Configs related to difficult changes
[difficulty]
	#If the difficulty should be set on world load
	#If true difficulty changes in game will also be saved to the config
	set_difficulty = true
	#The difficulty to set if 'set_difficulty' is true, respects if the difficulty is locked or not for the world
	#Allowed Values: PEACEFUL, EASY, NORMAL, HARD
	difficulty = "NORMAL"
	#If true the world will be set to hardcore, difficultly will be set to hard independent to the 'difficulty' config
	#Setting it to hardcore auto locks the difficulty while this is true
	hardcore = false
	#If a world's difficulty should be locked when loaded, if world already is locked it can't be changed
	#If the global world difficulty is enabled it's set first
	lock_difficulty = false

#A collection of misc configs
[misc]
	#If gamerules should be saved to config on world unload
	save_gamerules = false
	#A comma separated list of commands to run on world join, @p is replaced with joining player name, command is run by the server
	#Example: default_commands = ["/tellraw @p [\"\",{\"text\":\"Hi \"},{\"text\":\"@p\",\"color\":\"aqua\"}]"]
	default_commands = []

