name: "🥞 Check"

on:
  workflow_dispatch:
  push:

jobs:
  modpack22:
    runs-on: ubuntu-latest
    name: "📦 Test Modpack"
    steps:
      - name: "🔁 Checkout"
        uses: actions/checkout@v4
      - name: "🚀 Setup Go"
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: "🔰 Install Packwiz"
        run: go install github.com/packwiz/packwiz@latest
      - name: "📦 Export Modpack"
        run: |
          mkdir build
          packwiz modrinth export --output build/uBingo-Modpack.mrpack
          zip -r build/uBingo-Server.zip server/*
      - name: "🐋 Upload Modpack"
        uses: actions/upload-artifact@v4
        with:
          name: modpack
          path: build/*
