name: "🖱️ Testing"

on:
  workflow_dispatch:

jobs:
  modpack-info:
    runs-on: ubuntu-latest
    outputs:
      projectname: ${{ steps.info.outputs.projectname }}
      version: ${{ steps.info.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}
    name: "📙 Modpack Info"
    steps:
      - name: "🔁 Checkout"
        uses: actions/checkout@v2
      - name: "💾 Get modpack info"
        id: info
        run: |
            manifestjson=`cat ./modpack/manifest.json`
            projectname=`echo $(jq -r '.name' <<< "$manifestjson")`
            echo "::set-output name=projectname::$projectname"
            version=`echo $(jq -r '.minecraft.version' <<< "$manifestjson")`
            echo "::set-output name=version::$version"
      - name: "📛 Get tag"
        id: version
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

  changelog:
    runs-on: ubuntu-latest
    name: "📜 Changelog"
    outputs:
      changelog: ${{steps.changelog.outputs.changelog}}
    steps:
      - name: "🔁 Checkout"
        uses: actions/checkout@v2
      - name: "✍️ Write Changelogs"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v2.7.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "💽 Save changelog"
        run: "echo ${{steps.changelog.outputs.changelog}}"

  build:
    runs-on: ubuntu-latest
    needs: [changelog, modpack-info]
    name: "📦 Build"
    steps:
      - name: "🔁 Checkout"
        uses: actions/checkout@v2
      - name: "🚀 Download PAX"
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: froehlichA/pax
          file: "pax"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "🚢 Export modpack"
        run: |
          sudo chmod +x ./pax
          ./pax export
      - name: "🏹 Rename zip"
        run: |
          mv .out/${{ needs.modpack-info.outputs.projectname }}.zip .out/${{ needs.modpack-info.outputs.projectname }}-dev.zip
      - name: "🔼 Upload zip"
        uses: actions/upload-artifact@v2
        with:
          name: modpack
          path: .out/${{ needs.modpack-info.outputs.projectname }}-dev.zip
      - uses: MCJack123/ghaction-generate-release-hashes@v1 
        with:
          hash-type: sha256 
          file-name: hashes.txt 
      - uses: actions/upload-artifact@v2
        with: 
          name: Asset Hashes
          path: hashes.txt
